### PR TITLE
fix: make options immutable

### LINKED ISSUE #330: FindCursorContext.options are shared between requests and affect the output
If I reuse a single instance of `MongoClient` between independent requests, a `limit` value of one request limits the number of items of the second request.

I use a single client for all my requests:

```typescript
const FIND_OPTIONS: FindOptions = { noCursorTimeout: false };

const client = new MongoClient();

try {
  await client.connect({ ... });
} catch (err) {
  console.error('Error connecting to MongoDB', err);
  throw err;
}

const database = () => {
  return client.database("test");
};
```

First request has the `limit` call:
```typescript
export const allPositions = async (limit: number, offset: number) => {
  const db = database();

  const positions = db.collection<PositionSchema>("positions");

  return await positions.find(filter, FIND_OPTIONS).skip(offset).limit(limit).toArray();
}
```

Second request is supposed to return all items:
```typescript
export const allLocations = async () => {
  const db = database();

  const locations = db.collection<PositionSchema>("locations");

  const items = await locations.find({}, FIND_OPTIONS).toArray();

  return items;
}
```

Output:
- **/allLocations** Returns 70 locations (70/70)
- **/allPositions?limit=30** Returns 30 positions
- **/allLocations** Returns 30 locations (30/70)
- **/allPositions?limit=5** Returns 5 positions (because `limit` equals to `5)
- **/allLocations** Returns 5 locations (5/70)

If this is the expected behavior, how should I manage the MongoDB connections then?

### PR DESCRIPTION
**Pull request by FSou1**
fixes #330

### CODE REVIEW

File: src/collection/commands/find.ts [hunk 1]
```diff
@@ -33,17 +33,26 @@ export class FindCursor<T> extends CommandCursor<T> {
   }
 
   limit(limit: number): this {
-    this.#context.options.limit = limit;
+    this.#context.options = {
```
Comment (erfanium) [inline src/collection/commands/find.ts:36]: Why not clone the `context` object at constructor instead?

**Review by erfanium — CHANGES_REQUESTED** [review]

File: src/collection/commands/find.ts (hunk 1 above)
Comment (FSou1) [reply src/collection/commands/find.ts:36]: In this case the added unit test will fail, because the options object will have the limit value equals to 10.

Are you ok with updating the `options` parameter?

Comment (FSou1) [reply src/collection/commands/find.ts:36]: This could be the fix:

```typescript
  constructor(context: FindCursorContext) {
    super(context.protocol, () => this.executor());
    this.#context = {
      ...context,
      options: {
        ...context.options
      }
    };
  }
```

Let me know if you prefer it over the original changes.

Comment (FSou1) [reply src/collection/commands/find.ts:36]: Last but not least, we can move the fix to the `find` method by changing:

```typescript
  find(
    filter?: Filter<T>,
    options?: FindOptions,
  ): FindCursor<T> {
    return new FindCursor<T>({
      filter,
      protocol: this.#protocol,
      collectionName: this.name,
      dbName: this.#dbName,
      options: options ?? {},
    });
  }
```

this line `options: options ?? {}` with this one: `options: options ? {...options} : {},`.

Comment (erfanium) [reply src/collection/commands/find.ts:36]:
```
constructor(context: FindCursorContext) {
  super(context.protocol, () => this.executor());
  this.#context = {
    ...context,
    options: {
      ...context.options
    }
  };
}
```
This looks good to me

**Review by erfanium — APPROVED** [review]

**Comment by erfanium** [comment]
Thank you!
